from distutils.core import setup
setup(
  name = 'orpim_api',
  packages = ['orpim_api'],
  version = '0.1',
  license='APL-1.0',
  description = 'A simple python wrapper for the orp.im URL shortener API',  
  author = 'ICTman1076',
  author_email = 'orpim.pypi@sorcerertech.co.uk',
  url = 'https://github.com/ICTman1076/orpim_api',
  download_url = 'https://github.com/ICTman1076/orpim_api/archive/0.1.tar.gz',
  keywords = ['URL shortener'],
  install_requires=[],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Internet',
    'License :: OSI Approved',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
  ],
)